config:
  bearer: D2Y3UEWBHHYI7IEPONWR7NM7YHNLPPSG
  version: 05/01/2018

definition:
  # INTENTS, 'i' FOR THE FIRST CHARACTER
  ig: greet
  ia: aboutme
  is: search
  # ENTITIES
  n: person_name
  t: things

# NUMBERED FORMAT NEED "start" AND "end" KEY:
start: 1
end: 4
data:
  1: \ig{Good morning guys!}
  2: \ia{Who are you?!!}
  3: \is{Give me information about \n{Gilfoyle}}
  4: who is \n{Dinesh}?
  5: who are you \n{dinesh}{Dinesh}?

# LIST FORMAT DOES NOT NEED "start" AND "end" KEY:
# data:
#   - \ig{Good afternoon guys!}
#   - \ia{Who the hell are you?!!}
#   - \is{Give me any information about \n{Gil}{Gilfoyle}}
#   - \is{where is I can find King \n{Dinesh}}?